apiVersion: v1
kind: Service
metadata:
  name: mistral-7b-instruct
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: grpc
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: metrics
    port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    model: mistral-7b-instruct
  type: ClusterIP
